In [1]:
from pymongo import MongoClient
import pandas as pd

In [4]:
client = MongoClient("mongodb://root:rootpass@mongo:27017")

Protocolo	mongodb://	O "idioma" que a aplicação vai usar para conversar com o banco.

Usuário	root	A credencial de acesso (quem está tentando entrar).

Senha	rootpass	A chave secreta desse usuário.

Host	mongo	Onde o banco está rodando (pode ser um IP ou o nome de um container Docker).

Porta	27017	A "porta" específica do servidor que o MongoDB está escutando.

In [6]:
db = client["loja"]
produtos = db["produtos"]

In [10]:
produtos.insert_many([
{"nome":"Mouse Logitech","categoria":"Informática","preco":120,"estoque":50,"avaliacoes":[4,4,5],"disponivel":True},
{"nome":"Teclado Mecânico","categoria":"Informática","preco":350,"estoque":20,"avaliacoes":[5,5,4],"disponivel":True},
{"nome":"Smartphone Samsung","categoria":"Celulares","preco":2200,"estoque":15,"avaliacoes":[5,4,4],"disponivel":True},
{"nome":"Smartphone Xiaomi","categoria":"Celulares","preco":1800,"estoque":0,"avaliacoes":[4,4,4],"disponivel":False},
{"nome":"Fone Bluetooth","categoria":"Acessórios","preco":250,"estoque":30,"avaliacoes":[4,3,4],"disponivel":True},
{"nome":"Monitor LG","categoria":"Informática","preco":1200,"estoque":8,"avaliacoes":[5,5,5],"disponivel":True},
{"nome":"Carregador USB-C","categoria":"Acessórios","preco":80,"estoque":40,"avaliacoes":[4,4,3],"disponivel":True},
{"nome":"Tablet Lenovo","categoria":"Tablets","preco":1500,"estoque":5,"avaliacoes":[4,5,4],"disponivel":True},
{"nome":"Smartwatch Xiaomi","categoria":"Wearables","preco":900,"estoque":12,"avaliacoes":[4,4,5],"disponivel":True}
])

InsertManyResult([ObjectId('69b362f7d941cc63cd30d585'), ObjectId('69b362f7d941cc63cd30d586'), ObjectId('69b362f7d941cc63cd30d587'), ObjectId('69b362f7d941cc63cd30d588'), ObjectId('69b362f7d941cc63cd30d589'), ObjectId('69b362f7d941cc63cd30d58a'), ObjectId('69b362f7d941cc63cd30d58b'), ObjectId('69b362f7d941cc63cd30d58c'), ObjectId('69b362f7d941cc63cd30d58d')], acknowledged=True)

In [11]:
for item in produtos.find():
    print(item)

{'_id': ObjectId('69b36283d941cc63cd30d583')}
{'_id': ObjectId('69b36298d941cc63cd30d584')}
{'_id': ObjectId('69b362f7d941cc63cd30d585'), 'nome': 'Mouse Logitech', 'categoria': 'Informática', 'preco': 120, 'estoque': 50, 'avaliacoes': [4, 4, 5], 'disponivel': True}
{'_id': ObjectId('69b362f7d941cc63cd30d586'), 'nome': 'Teclado Mecânico', 'categoria': 'Informática', 'preco': 350, 'estoque': 20, 'avaliacoes': [5, 5, 4], 'disponivel': True}
{'_id': ObjectId('69b362f7d941cc63cd30d587'), 'nome': 'Smartphone Samsung', 'categoria': 'Celulares', 'preco': 2200, 'estoque': 15, 'avaliacoes': [5, 4, 4], 'disponivel': True}
{'_id': ObjectId('69b362f7d941cc63cd30d588'), 'nome': 'Smartphone Xiaomi', 'categoria': 'Celulares', 'preco': 1800, 'estoque': 0, 'avaliacoes': [4, 4, 4], 'disponivel': False}
{'_id': ObjectId('69b362f7d941cc63cd30d589'), 'nome': 'Fone Bluetooth', 'categoria': 'Acessórios', 'preco': 250, 'estoque': 30, 'avaliacoes': [4, 3, 4], 'disponivel': True}
{'_id': ObjectId('69b362f7d941cc63cd30d58a'), 'nome': 'Monitor LG', 'categoria': 'Informática', 'preco': 1200, 'estoque': 8, 'avaliacoes': [5, 5, 5], 'disponivel': True}
{'_id': ObjectId('69b362f7d941cc63cd30d58b'), 'nome': 'Carregador USB-C', 'categoria': 'Acessórios', 'preco': 80, 'estoque': 40, 'avaliacoes': [4, 4, 3], 'disponivel': True}
{'_id': ObjectId('69b362f7d941cc63cd30d58c'), 'nome': 'Tablet Lenovo', 'categoria': 'Tablets', 'preco': 1500, 'estoque': 5, 'avaliacoes': [4, 5, 4], 'disponivel': True}
{'_id': ObjectId('69b362f7d941cc63cd30d58d'), 'nome': 'Smartwatch Xiaomi', 'categoria': 'Wearables', 'preco': 900, 'estoque': 12, 'avaliacoes': [4, 4, 5], 'disponivel': True}

In [12]:
for item in produtos.find({"preco" : {"$gt" : 500}}):
    print(item)

{'_id': ObjectId('69b362f7d941cc63cd30d587'), 'nome': 'Smartphone Samsung', 'categoria': 'Celulares', 'preco': 2200, 'estoque': 15, 'avaliacoes': [5, 4, 4], 'disponivel': True}
{'_id': ObjectId('69b362f7d941cc63cd30d588'), 'nome': 'Smartphone Xiaomi', 'categoria': 'Celulares', 'preco': 1800, 'estoque': 0, 'avaliacoes': [4, 4, 4], 'disponivel': False}
{'_id': ObjectId('69b362f7d941cc63cd30d58a'), 'nome': 'Monitor LG', 'categoria': 'Informática', 'preco': 1200, 'estoque': 8, 'avaliacoes': [5, 5, 5], 'disponivel': True}
{'_id': ObjectId('69b362f7d941cc63cd30d58c'), 'nome': 'Tablet Lenovo', 'categoria': 'Tablets', 'preco': 1500, 'estoque': 5, 'avaliacoes': [4, 5, 4], 'disponivel': True}
{'_id': ObjectId('69b362f7d941cc63cd30d58d'), 'nome': 'Smartwatch Xiaomi', 'categoria': 'Wearables', 'preco': 900, 'estoque': 12, 'avaliacoes': [4, 4, 5], 'disponivel': True}

In [13]:
dados = list(produtos.find())
dados

[{'_id': ObjectId('69b36283d941cc63cd30d583')},
 {'_id': ObjectId('69b36298d941cc63cd30d584')},
 {'_id': ObjectId('69b362f7d941cc63cd30d585'),
  'nome': 'Mouse Logitech',
  'categoria': 'Informática',
  'preco': 120,
  'estoque': 50,
  'avaliacoes': [4, 4, 5],
  'disponivel': True},
 {'_id': ObjectId('69b362f7d941cc63cd30d586'),
  'nome': 'Teclado Mecânico',
  'categoria': 'Informática',
  'preco': 350,
  'estoque': 20,
  'avaliacoes': [5, 5, 4],
  'disponivel': True},
 {'_id': ObjectId('69b362f7d941cc63cd30d587'),
  'nome': 'Smartphone Samsung',
  'categoria': 'Celulares',
  'preco': 2200,
  'estoque': 15,
  'avaliacoes': [5, 4, 4],
  'disponivel': True},
 {'_id': ObjectId('69b362f7d941cc63cd30d588'),
  'nome': 'Smartphone Xiaomi',
  'categoria': 'Celulares',
  'preco': 1800,
  'estoque': 0,
  'avaliacoes': [4, 4, 4],
  'disponivel': False},
 {'_id': ObjectId('69b362f7d941cc63cd30d589'),
  'nome': 'Fone Bluetooth',
  'categoria': 'Acessórios',
  'preco': 250,
  'estoque': 30,
  'avaliacoes': [4, 3, 4],
  'disponivel': True},
 {'_id': ObjectId('69b362f7d941cc63cd30d58a'),
  'nome': 'Monitor LG',
  'categoria': 'Informática',
  'preco': 1200,
  'estoque': 8,
  'avaliacoes': [5, 5, 5],
  'disponivel': True},
 {'_id': ObjectId('69b362f7d941cc63cd30d58b'),
  'nome': 'Carregador USB-C',
  'categoria': 'Acessórios',
  'preco': 80,
  'estoque': 40,
  'avaliacoes': [4, 4, 3],
  'disponivel': True},
 {'_id': ObjectId('69b362f7d941cc63cd30d58c'),
  'nome': 'Tablet Lenovo',
  'categoria': 'Tablets',
  'preco': 1500,
  'estoque': 5,
  'avaliacoes': [4, 5, 4],
  'disponivel': True},
 {'_id': ObjectId('69b362f7d941cc63cd30d58d'),
  'nome': 'Smartwatch Xiaomi',
  'categoria': 'Wearables',
  'preco': 900,
  'estoque': 12,
  'avaliacoes': [4, 4, 5],
  'disponivel': True}]

In [14]:
df_produtos = pd.DataFrame(dados)
df_produtos.head()

,_id,nome,categoria,preco,estoque,avaliacoes,disponivel
0,69b36283d941cc63cd30d583,NaN,NaN,NaN,NaN,NaN,NaN
1,69b36298d941cc63cd30d584,NaN,NaN,NaN,NaN,NaN,NaN
2,69b362f7d941cc63cd30d585,Mouse Logitech,Informática,120.0,50.0,"[4, 4, 5]",True
3,69b362f7d941cc63cd30d586,Teclado Mecânico,Informática,350.0,20.0,"[5, 5, 4]",True
4,69b362f7d941cc63cd30d587,Smartphone Samsung,Celulares,2200.0,15.0,"[5, 4, 4]",True

In [15]:
df_produtos = df_produtos.drop(columns=["_id"])
df_produtos.head(3)

             nome    categoria  preco  estoque avaliacoes disponivel
0             NaN          NaN    NaN      NaN        NaN        NaN
1             NaN          NaN    NaN      NaN        NaN        NaN
2  Mouse Logitech  Informática  120.0     50.0  [4, 4, 5]       True

In [23]:
df_produtos["media_avaliacoes"] = df_produtos["avaliacoes"].apply(lambda x: sum(x)/len(x))
df_produtos.head(3)

TypeError: 'float' object is not iterable

In [ ]:
produtos_p = db["produtos_processados"]

In [ ]:
dados_p = df_produtos.to_dict("records")
dados_p

In [ ]:
produtos_p.insert_many(dados_p)

In [ ]:
for item in produtos_p.find():
    print(item)